### PR TITLE
Update to AWS v3

### PR DESCRIPTION
**Pull request by bakura10**
Replaces #90 and #91

### CODE REVIEW

**Comment by jessertaylor** [comment]
Thanks for sorted this - I see travis is failing with

`Zend\ServiceManager\Exception\InvalidServiceNameException: A service by the name or alias "ServiceListener" already exists and cannot be overridden, please use an alternate name`

I have not looked through the code yet, let me know if you need a hand I was was hoping you may have an idea though :)

**Comment by bakura10** [comment]
Yeah... That's a strange error ôÔ. Tests were passing previously, I didn't change anything! I'll have a look but if you have some time to see why this error is triggered, I'd be super happy :p

**Comment by jessertaylor** [comment]
I've had a look at the bootstrapping code for the tests - this line here

https://github.com/juriansluiman/SlmMail/blob/master/tests/SlmMailTest/Util/ServiceManagerFactory.php#L77

I'm not really sure why this is being set - in Ocramius's original code he isn't doing this. https://gist.github.com/Ocramius/3994325#file-servicemanagerfactory-php-L55

I'm wondering if we could just take it out?

Jesse

**Comment by bakura10** [comment]
Even removing this does not seem to resolve the issue.

To be honest the way this library was tested is wrong, but as I'm working on a more lightweight mail system (https://github.com/zf-fr/zfr-mail) I don't have so much time to invest on this :).

**Comment by bakura10** [comment]
I'm wondering if the issue does not come from the latest versions of Zend-Mvc (v2.7), that introduces several changes....

**Comment by jessertaylor** [comment]
Shouldn't this be AwsModule instead of Aws (they changed it in v3)

https://github.com/juriansluiman/SlmMail/blob/master/tests/TestConfiguration.php.dist#L21

**Comment by jessertaylor** [comment]
Sorry, yes you are right - I'm pretty sure I am able to get past the error travis is failing on when I run phpunit (I'm running it against ZF2/mvc 2.4 I believe)

**Comment by jessertaylor** [comment]
I believe we're definitely closer to the tests working unless there were lots of changes in v3 :) I believe we need to pass the SesClient a config which contains a region (eu-west-1) and possibly a version also (but looking at code I think the region might only be needed)

**Comment by vincequeiroz** [comment]
I tried update SesTransportTest, but I don't know how do.

The AWS SES support another regions, and require the config:
```
        [
            'region'  => 'us-east-1',
            'version' => 'latest'
        ]
```

We must fix documentation in block:

> As the date of writing, Amazon SES is only supported in "us-east-1" region. Make sure to reflect this into your AWS config parameters.

https://github.com/juriansluiman/SlmMail/blob/master/docs/Ses.md#user-content-amazon-ses
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html#region-and-version-options-are-now-required
http://docs.aws.amazon.com/general/latest/gr/rande.html#ses_region

**Comment by jackdpeterson** [comment]
Replaced by #105

**Comment by bakura10** [comment]
Address

**Pull request closed without merging**
