### PR TITLE
Fixed Aws service usage in SesServiceFactory to match changes in zf2 …

### PR DESCRIPTION
**Pull request by zmicier**
…module and sdk

### CODE REVIEW

**Comment by zmicier** [comment]
Any chances to update required PHP version to 5.5? Aws Sdk was changed lately:
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html
and already using features like class name resolution via ::class.

**Comment by bakura10** [comment]
Hi,

What does this fix? Upgrading to latest SDK is definitely something I'd love, as well as upgrading the minimum dependency of this package to PHP 5.5. This will require a BC break but this is worth it.

I know it will aks you a bit more work but could you handle all this? (upgrading dependency, upgrading AWS module to v2 (https://github.com/juriansluiman/SlmMail/blob/master/composer.json#L38) which will give you access to AWS SDK v3 :).

Thanks!

**Comment by zmicier** [comment]
This is the minimal change to make SlmMail work with latest Aws sdk (3.3.7) The key in service manager for Sdk was changed in AWS ZF2 module (you must remember it as it was your change) and now the recommended way (by amazon) to get access to the services is by factory method like: $sdk->createSes(); etc.

I have tested it for simple text messages and it is works ok for me, but attachments, mime parts, and other things must still be tested and probably fixed. I can find some time during the weekend to test it, as I plan to use it in the current project I am working on.

**Comment by bakura10** [comment]
Ha yeah you're right. However you need to update the composer json to require the v2 of the module. For someone using the v1 of the module he will get v2 of aws sdk and therefore this code will fail.

And yes I'd like of you could try it on your end before we merge that, as I'm not using ses :)

**Comment by bakura10** [comment]
Replaced by #97

**Comment by bakura10** [comment]
This has been fixed by #105

**Pull request closed without merging**
