### PR TITLE
AWS Sdk for PHP v3 support

### LINKED ISSUE #90: SES - Enhancement request: switch to latest Aws ZF2 module
It appears that this is presently undocumented so I'll at least list this as an issue. This module depends on the older version of the AWS ZF2 module and not on the latest version.

Converting to a newer version looks to be as simple as modifying SesServiceFactory to:
```
namespace SlmMail\Factory;

use SlmMail\Service\SesService;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use Aws\Sdk;

class SesServiceFactory implements FactoryInterface
{

    /**
     *
     * {@inheritDoc}
     *
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        return new SesService($serviceLocator->get(Sdk::class)->createSes());
    }
}
```

Is this something that is planned in the near future? I realize that this may also affect other modules like SlmQueue and should probably be committed in parallel for projects that depends on both SlmQueue as well as SlmMail.

### PR DESCRIPTION
**Pull request by jackdpeterson**
Resolves #90 and #103

### CODE REVIEW

**Comment by jackdpeterson** [comment]
A few things to note:

1. This resolves some warnings from phpunit about the getMock versus createMock (the suggested way).

2. I'm assuming that this will be a 2.0.0 tagged bump due to BC breakage.

3. I'm assuming that setting the minimum to PHP 5.6 is perfectly acceptable because even phpunit complains about 5.5. Furthermore, major distributions of linux are now including php 7 at this juncture and providing legacy support for security-only versions of PHP is sub-optimal from a forward-looking perspective.

**Comment by jackdpeterson** [comment]
ping @bakura10 on merging this in

**Comment by bakura10** [comment]
Looks pretty nice to me!

**Comment by bakura10** [comment]
Tagged as 2.0.0.

Thanks!

**Comment by jackdpeterson** [comment]
Thanks for the quick merge :-)

**Pull request merged**
