### PR TITLE
fix http 414 error when sending big html messages.

### PR DESCRIPTION
**Pull request by mariojrrc**
The /send endpoint tell us to use POST instead of GET when sending a message. I've identified this issue when a tried to send a big html message.

https://elasticemail.com/support/http-api/send/

### CODE REVIEW

**Comment by mariojrrc** [comment]
Could you take a look at this request @bakura10 ?

**Comment by bakura10** [comment]
That looks good! Thanks.

**Comment by bakura10** [comment]
Could you please do another PR to update the changelog (mark it as 2.1.2). Thanks a lot ! :)

**Comment by mariojrrc** [comment]
Done :)

**Pull request merged**
