### PR TITLE
Let's stay up to date with v3 of the mailgun api

### PR DESCRIPTION
**Pull request by companyou**

### CODE REVIEW

**Comment by bakura10** [comment]
Thanks for the PR!

None of the API call has changed?

**Comment by companyou** [comment]
v3 is BC
http://blog.mailgun.com/default-api-version-now-v3/

Just better speed, and more features ;).

**Comment by bakura10** [comment]
Awesome. Thanks!

**Comment by bakura10** [comment]
I've tagged SlmMail as v1.6.0.

**Comment by companyou** [comment]
Damn dude,
That was fast.
Awesome!
Updating my vendor now to use this release :+1:

**Comment by bakura10** [comment]
You're welcome :).

**Pull request merged**
